// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7B_t3YZzxmvuwh1CuacFhqpYkDUmFGps',
    appId: '1:955982188623:web:268ac5ca3621c42a181a3a',
    messagingSenderId: '955982188623',
    projectId: 'flutter-shopping-d5fe5',
    authDomain: 'flutter-shopping-d5fe5.firebaseapp.com',
    storageBucket: 'flutter-shopping-d5fe5.appspot.com',
    measurementId: 'G-4VTPTKCYQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_xhFWzjeSg3-FJU9GJ7RRV8r8JcaoXU',
    appId: '1:955982188623:android:e6b1981c6b56a7b3181a3a',
    messagingSenderId: '955982188623',
    projectId: 'flutter-shopping-d5fe5',
    storageBucket: 'flutter-shopping-d5fe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNYJUYh2XU_wr7nSyAamTW6nhtrr-F-Z8',
    appId: '1:955982188623:ios:48367680d64f605e181a3a',
    messagingSenderId: '955982188623',
    projectId: 'flutter-shopping-d5fe5',
    storageBucket: 'flutter-shopping-d5fe5.appspot.com',
    iosBundleId: 'com.example.flutterShoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNYJUYh2XU_wr7nSyAamTW6nhtrr-F-Z8',
    appId: '1:955982188623:ios:48367680d64f605e181a3a',
    messagingSenderId: '955982188623',
    projectId: 'flutter-shopping-d5fe5',
    storageBucket: 'flutter-shopping-d5fe5.appspot.com',
    iosBundleId: 'com.example.flutterShoppingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7B_t3YZzxmvuwh1CuacFhqpYkDUmFGps',
    appId: '1:955982188623:web:863d6c05d566ec6a181a3a',
    messagingSenderId: '955982188623',
    projectId: 'flutter-shopping-d5fe5',
    authDomain: 'flutter-shopping-d5fe5.firebaseapp.com',
    storageBucket: 'flutter-shopping-d5fe5.appspot.com',
    measurementId: 'G-KQ8T3M344V',
  );
}
